# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/appmod-with-genai',
                'doc_host': 'https://jihed.github.io',
                'git_url': 'https://github.com/jihed/appmod-with-genai',
                'lib_path': 'appmod_with_genai'},
  'syms': { 'appmod_with_genai.appmod_with_genai': { 'appmod_with_genai.appmod_with_genai.foo': ( 'appmod_with_genai_start.html#foo',
                                                                                                  'appmod_with_genai/appmod_with_genai.py')},
            'appmod_with_genai.core': {'appmod_with_genai.core.foo': ('core.html#foo', 'appmod_with_genai/core.py')}}}
